### ISSUE TITLE
not changed NM1 landmark accordingly, it is why 1_F is better?

### ISSUE THREAD

**Issue by tengshaofeng** [luoyetx/deep-landmark#28]
Hi,
    i am so appreciated with your great work.

here comes my two question:
# code from dataset/level1.py
1,      nm_face = cv2.resize(nm_face, (31, 39)).reshape((1, 31, 39))
        nm_landmark = landmarkGt[2:, :].reshape((6))
        NM_imgs.append(nm_face)
This code  seems keep the landmark same between the F_face and the nm_face except the dimension. But I think nm_landmark in y_axis shoud be (landmarkGt[2:, :]-8)/31, because in landmarkGt, point_y = y/39, 
point_y_new = (y-8)/31, suppose y is the abs location in (39,39) box.
    Isn't why 1-F is better than 1-F+1_NM+1_EN?

2,      f_bbox = bbox.subBBox(-0.05, 1.05, -0.05, 1.05)
        f_face = img[f_bbox.top:f_bbox.bottom+1,f_bbox.left:f_bbox.right+1]

this code changed the bbox to f_bbox, but does not changed the landmark accordingly. isn't a mistake? 
or just for add noise?

look forward to your reply. thanks

**Comment by luoyetx** [comment]
@tengshaofeng Sorry for the late reply.

1. It matters little whether you apply (y-8)/31 as the fully connected layer has the bias term and will learn this bias for all points. I'm not sure it is a training part or the data processing part that makes 1_F + 1_NM + 1_EN worse than a single 1_F.

2. The reason is the same. For bbox processing, I think some random perturbation will be better. I'm not having so much knowledge about deep learning that time 😂 .

**Comment by tengshaofeng** [comment]
thanks for your reply
